name: Enable Multilingual Support
description: Installs and configures the necessary Drupal core modules to enable multilingual support with the provided language.
install:
  - language
  - content_translation
  - locale
  - config_translation
